#!/usr/bin/env node
/**
 * Generate browser-openable copies of the extension pages for review.
 *
 * The generated pages are the real HTML with one change: the entry module is
 * loaded by the preview harness instead of directly, so `chrome.*` can be stubbed
 * and a week of sample data seeded first. Generating them rather than maintaining
 * them by hand means the preview can never drift from what ships.
 *
 * Output is gitignored and excluded from the store package.
 *
 *   node tools/make-preview.mjs
 *   python3 -m http.server 8137   # from the repository root
 *   open http://localhost:8137/extension/src/ui/dashboard/preview.html
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const PAGES = [
  'extension/src/ui/dashboard/dashboard.html',
  'extension/src/ui/popup/popup.html',
];

const MODULE_SCRIPT = /[ \t]*<script\s+type="module"\s+src="([^"]+)"><\/script>\s*/;

for (const page of PAGES) {
  const source = readFileSync(join(ROOT, page), 'utf8');
  const match = source.match(MODULE_SCRIPT);
  if (!match) {
    console.error(`✗ ${page}: no <script type="module" src="…"> found`);
    process.exitCode = 1;
    continue;
  }

  const entry = match[1];

  // Relative, not server-absolute: the same generated page then works from a
  // local file, from a server root, and from a GitHub Pages project subpath.
  const toRoot = relative(dirname(join(ROOT, page)), ROOT).split(sep).join('/');
  const harnessDir = `${toRoot}/preview`;

  const harness = [
    '  <!-- Generated by tools/make-preview.mjs — do not edit, do not ship. -->',
    `  <script>window.__BILLED_PREVIEW_ENTRY__ = ${JSON.stringify(entry)};</script>`,
    `  <script src="${harnessDir}/mock-chrome.js"></script>`,
    `  <script src="${harnessDir}/seed.js"></script>`,
    '',
  ].join('\n');

  const out = source.replace(MODULE_SCRIPT, `\n${harness}`);
  const target = join(dirname(join(ROOT, page)), 'preview.html');
  writeFileSync(target, out);
  console.log(`  ${relative(ROOT, target)}  (entry: ${entry})`);
}

console.log('\nServe the repository root, then open:');
console.log('  /extension/src/ui/dashboard/preview.html');
console.log('  /extension/src/ui/popup/preview.html');
console.log('\nQuery parameters: ?plan=free, ?now=1 · Hashes: #clients, #settings, #welcome');
