#!/usr/bin/env node
/**
 * Generate a batch of offline licence keys.
 *
 * Why this exists: a payment processor is not always available — KYC takes days,
 * and an Indian seller starting out may simply want to accept UPI into their own
 * account and hand a key over by message. That needs licence keys that can be
 * checked with no server at all.
 *
 * How it stays honest:
 *   - Only the SHA-256 hashes go into the extension, so the shipped code cannot
 *     be read to recover the keys.
 *   - The plaintext list is written to keys/, which is gitignored. It never
 *     leaves the seller's machine.
 *   - Keys use an alphabet with no 0/O/1/I/L, because these get read out over the
 *     phone and typed by hand.
 *
 * Verification is a hash lookup, so it works offline, forever, with no account.
 * A buyer who publishes their key can be shared — that is true of every
 * client-side licence on earth, and is not the problem worth solving today.
 *
 *   node tools/make-keys.mjs            # 300 keys, batch 1
 *   node tools/make-keys.mjs 500 2      # 500 keys, batch 2
 */

import { createHash, randomInt } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const COUNT = Number(process.argv[2]) || 300;
const BATCH = Number(process.argv[3]) || 1;

/** No 0, O, 1, I or L — these are the characters people mistype. */
const ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
const GROUPS = 3;
const GROUP_LENGTH = 5;
const PREFIX = 'BILLED';

/** Truncated to 128 bits: still far beyond guessable, and keeps the file small. */
const HASH_CHARS = 32;

function randomGroup() {
  let out = '';
  for (let i = 0; i < GROUP_LENGTH; i += 1) out += ALPHABET[randomInt(ALPHABET.length)];
  return out;
}

function makeKey() {
  return `${PREFIX}-${Array.from({ length: GROUPS }, randomGroup).join('-')}`;
}

/** Must match canonicaliseKey() in extension/src/core/offline-keys.js exactly. */
function canonical(key) {
  return key.toUpperCase().replace(/[^0-9A-Z]/g, '');
}

function hashOf(key) {
  return createHash('sha256').update(canonical(key), 'utf8').digest('hex').slice(0, HASH_CHARS);
}

const keys = new Set();
while (keys.size < COUNT) keys.add(makeKey());
const list = [...keys];
const hashes = list.map(hashOf).sort();

if (new Set(hashes).size !== hashes.length) {
  console.error('Hash collision — rerun.');
  process.exit(1);
}

// ---------------------------------------------------------------- hashes (shipped)

const module_ = `/**
 * Offline licence keys — hashes only.
 *
 * GENERATED by tools/make-keys.mjs. Do not edit by hand.
 * Batch ${BATCH} · ${list.length} keys · generated ${new Date().toISOString().slice(0, 10)}
 *
 * These are SHA-256 hashes (truncated to 128 bits) of the keys that were sold
 * directly. The keys themselves are not here and cannot be recovered from this
 * file. Verification is a local lookup, so an offline licence needs no server,
 * no account and no network permission — it keeps working forever.
 */

export const OFFLINE_KEY_BATCH = ${BATCH};

const HASHES = new Set([
${hashes.map((hash) => `  '${hash}',`).join('\n')}
]);

/** Strip formatting so a key pasted with spaces, dashes or lower case still works. */
export function canonicaliseKey(key) {
  return String(key || '').toUpperCase().replace(/[^0-9A-Z]/g, '');
}

/** Shape check before hashing, so obvious typos fail fast with a clear message. */
export function looksLikeOfflineKey(key) {
  const value = canonicaliseKey(key);
  return value.startsWith('${PREFIX}') && value.length === ${PREFIX.length + GROUPS * GROUP_LENGTH};
}

async function sha256Hex(text) {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('');
}

/**
 * Is this one of the keys we issued?
 * @returns {Promise<boolean>}
 */
export async function verifyOfflineKey(key) {
  if (!looksLikeOfflineKey(key)) return false;
  const hash = await sha256Hex(canonicaliseKey(key));
  return HASHES.has(hash.slice(0, ${HASH_CHARS}));
}
`;

const modulePath = join(ROOT, 'extension/src/core/offline-keys.js');
mkdirSync(dirname(modulePath), { recursive: true });
writeFileSync(modulePath, module_);

// ---------------------------------------------------------------- plaintext (private)

const ledger = [
  `BILLED — OFFLINE LICENCE KEYS — BATCH ${BATCH}`,
  `Generated ${new Date().toISOString().slice(0, 10)} · ${list.length} keys`,
  '',
  'KEEP THIS FILE PRIVATE. Anyone holding a key can unlock Pro.',
  'It is gitignored on purpose — never commit it, never paste it in a chat.',
  '',
  'HOW TO USE',
  '  1. Customer pays you (UPI, bank transfer, however).',
  '  2. Send them the next unused key below.',
  '  3. Write their email and the date next to it, so you know what you sold.',
  '  4. They paste it into Billed: Settings -> Plan -> Activate.',
  '',
  'Keys work offline and never expire. Nothing is sent anywhere.',
  '',
  `${'-'.repeat(64)}`,
  '  #    KEY                        SOLD TO                DATE',
  `${'-'.repeat(64)}`,
  ...list.map((key, index) => `  ${String(index + 1).padStart(3)}  ${key}   ${'.'.repeat(20)}   ${'.'.repeat(10)}`),
  '',
].join('\n');

const ledgerPath = join(ROOT, 'keys', `billed-keys-batch-${BATCH}.txt`);
mkdirSync(dirname(ledgerPath), { recursive: true });
writeFileSync(ledgerPath, ledger);

console.log(`Generated ${list.length} keys (batch ${BATCH})\n`);
console.log(`  ${relative(ROOT, modulePath)}   hashes only — safe to commit and ship`);
console.log(`  ${relative(ROOT, ledgerPath)}   PLAINTEXT — gitignored, keep private\n`);
console.log('First three, so you can test one right away:');
for (const key of list.slice(0, 3)) console.log(`  ${key}`);
